# Generated by Django 4.2.4 on 2023-09-04 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0004_alter_publisher_id'),
        ('author', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('book_title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('book_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='book_title', unique=True, verbose_name='Slug')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Author')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Book Title',
                'verbose_name_plural': 'Books Title',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('book_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=24, unique=True, verbose_name='Book Id')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Qr Code')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.booktitle', verbose_name='Book Title')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
