# Generated by Django 4.2.4 on 2023-09-05 05:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_book_id_book_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_isbn',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=13, null=True, unique=True, verbose_name='Book Id'),
        ),
    ]
