# Generated by Django 4.2.4 on 2023-09-05 05:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('category_book_name', models.CharField(db_index=True, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=50, unique=True, verbose_name='Name')),
                ('category_book_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='category_book_name', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category Book',
                'verbose_name_plural': 'Categoryies Book',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=0, verbose_name='Available Copies'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('az', 'Azerbaijani'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('ny', 'Chichewa'), ('co', 'Corsican'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('eng', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('tl', 'Filipino'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('gl', 'Galician'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('kn', 'Canada'), ('kk', 'Kazakh'), ('ko', 'Korean'), ('la', 'Latin'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('cy', 'Welsh')], max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Pages Count'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.TextField(blank=True, help_text='Summary about the book', max_length=500, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('book_type', 'Book Type'), ('journal_type', 'Journal Type'), ('cartoon_herous_type', 'Cartoon Hereous Type')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='In Stock'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_book', to='book.categorybook', verbose_name='Category Book'),
        ),
    ]
