# Generated by Django 4.2.4 on 2023-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Published Date'),
        ),
    ]
