# Generated by Django 4.2.4 on 2023-09-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_edition_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktitle', to='book.booktitle', verbose_name='Book Title'),
        ),
    ]
