# Generated by Django 4.2.4 on 2023-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount'),
        ),
    ]
