# Generated by Django 4.2.4 on 2023-10-11 07:12

from django.db import migrations, models
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('publisher_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=20, null=True, unique=True, verbose_name='Publisher Id')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='Name')),
                ('publisher_country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
    ]
