# Generated by Django 4.2.4 on 2023-09-04 15:17

from django.db import migrations, models
import django_countries.fields
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.UUID('8620ba67-15d1-4849-b545-4bbfbe044d7e'), editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='Name')),
                ('publisher_country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
    ]
