# Generated by Django 4.2.4 on 2023-09-04 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='ps_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a1f9ed9-371e-4467-8933-ae23ac58bf95'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
