# Generated by Django 4.2.4 on 2023-09-04 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_publisher_ps_data_alter_publisher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='ps_data',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e39fcd61-049b-46f3-b607-82f41a733a00'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
