# Generated by Django 4.2.4 on 2023-09-04 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_remove_publisher_ps_data_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8e9c432-0884-4e3a-896a-9c74b625a536'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
