# Generated by Django 4.2.4 on 2023-09-05 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('970738f3-a235-4273-b54a-dd342d73b335'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
