# Generated by Django 4.2.4 on 2023-09-05 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11b02edc-1cdd-4ce6-acc7-29147c9694ac'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
