# Generated by Django 4.2.4 on 2023-09-05 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('060ecb5c-b845-45b5-9084-bb34e114f0ea'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
