# Generated by Django 4.2.4 on 2023-09-05 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2494522-f769-4a0e-8d28-e097de61e591'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
