# Generated by Django 4.2.4 on 2023-09-05 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b4c2044-cf5a-4311-a6ca-a0ae7b478758'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
