# Generated by Django 4.2.4 on 2023-09-05 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b0c95de-4ffb-46d3-9bc7-2a4a583f972e'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
