# Generated by Django 4.2.4 on 2023-09-05 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cde15349-cfe9-48d9-98f3-26554207f49f'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
