# Generated by Django 4.2.4 on 2023-09-05 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('343a64b7-70ac-4690-8181-5fe1ae975366'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
