# Generated by Django 4.2.4 on 2023-09-05 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22a525da-6a79-47c8-93ba-b06ed5e83efb'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
