# Generated by Django 4.2.4 on 2023-09-05 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0013_alter_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fdcb7ab-dbc7-4918-94de-0394c7164a72'), editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
