# Generated by Django 4.2.4 on 2023-09-05 05:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0015_alter_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=20, null=True, unique=True, verbose_name='Publisher Id'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
