# Generated by Django 4.2.4 on 2023-10-11 07:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rented_status', models.CharField(choices=[('#0', 'Rented'), ('#1', 'Returned'), ('#2', 'Lost'), ('#3', 'Delayed')], max_length=20, verbose_name='Status')),
                ('rental_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=24, unique=True, verbose_name='Rental Id')),
                ('rent_start_date', models.DateField(help_text='When the book was rented')),
                ('rent_end_date', models.DateField(blank=True, help_text='Deadline return borrowed books')),
                ('return_date', models.DateField(blank=True, help_text='Actual return date,user returned date', null=True)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('rented_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Book')),
                ('rented_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Rental Book',
                'verbose_name_plural': 'Rental Books',
                'ordering': ['-created'],
            },
        ),
    ]
