# Generated by Django 4.2.4 on 2023-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_end_date',
            field=models.DateField(blank=True, help_text='Deadline return borrowed books'),
        ),
    ]
