# Generated by Django 4.2.4 on 2023-09-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_rent_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created'], 'verbose_name': 'Rental Book', 'verbose_name_plural': 'Rental Books'},
        ),
    ]
