# Generated by Django 4.2.4 on 2023-09-05 04:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('customer_first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('customer_last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('customer_username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username')),
                ('customer_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='customer_username', unique=True, verbose_name='Slug')),
                ('customer_additional_information', models.TextField(blank=True, verbose_name='Additional Information')),
                ('customer_rating', models.PositiveSmallIntegerField(default=50, verbose_name='Rating')),
                ('customer_key', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=24, unique=True, verbose_name='Customer Id')),
                ('customer_book_count', models.PositiveSmallIntegerField(default=0, verbose_name='Book Count')),
                ('customer_books', models.ManyToManyField(blank=True, help_text='Books that are currently rented', to='book.book')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
