# Generated by Django 4.2.4 on 2023-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_book_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Book Count'),
        ),
    ]
